import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";

// Local-disk stand-in for real object storage -- single-instance only,
// same posture as rate-limit.ts's in-memory limiter: this app doesn't run
// multi-instance today, and this is the seam to swap for an S3 adapter
// once B7's real credentials land. Callers only ever see put/get/delete
// with an opaque storageKey; nothing above this file knows the bytes live
// on disk.

const UPLOADS_ROOT = path.resolve(process.env.UPLOADS_DIR ?? "./uploads");

function resolveKeyPath(storageKey: string): string {
  const resolved = path.resolve(UPLOADS_ROOT, storageKey);
  if (!resolved.startsWith(UPLOADS_ROOT + path.sep)) {
    // storageKey is always generated by putDocument below, never taken
    // directly from user input -- this is a defensive guard against a
    // future caller passing something path-traversal-shaped, not a
    // reachable case today.
    throw new Error(`Invalid storage key: ${storageKey}`);
  }
  return resolved;
}

// opportunityId scopes the on-disk layout for easy manual inspection;
// randomUUID + the original filename avoids collisions without needing a
// DB round-trip first to get a Document id.
export function buildStorageKey(opportunityId: string, filename: string): string {
  const safeName = filename.replace(/[^a-zA-Z0-9._-]+/g, "-");
  return path.join(opportunityId, `${randomUUID()}-${safeName}`);
}

export async function putObject(storageKey: string, bytes: Buffer): Promise<void> {
  const filePath = resolveKeyPath(storageKey);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, bytes);
}

export async function getObject(storageKey: string): Promise<Buffer> {
  return readFile(resolveKeyPath(storageKey));
}

export async function deleteObject(storageKey: string): Promise<void> {
  await rm(resolveKeyPath(storageKey), { force: true });
}
